#!/bin/sh

set -ev

cd src

echo -e '<!-- Autogenerated by build.sh, do not edit! -->' > mathjaxheader.html
echo -e '<span class="math inline" style="display: none">\n\\(' >> mathjaxheader.html
cat ../mathsymbols.sty | sed  's/providecommand/renewcommand/g' >> mathjaxheader.html
echo -e '\\)\n</span>' >> mathjaxheader.html
cd ..
# Rscript -e "bookdown::render_book('src/index.Rmd', 'bookdown::html_book')"
Rscript -e "bookdown::render_book('src/index.Rmd', 'bookdown::gitbook')"
Rscript -e "bookdown::render_book('src/index.Rmd', 'bookdown::pdf_book')"
# Rscript -e "bookdown::render_book('src/index.Rmd', 'bookdown::epub_book')"

