#!/bin/sh

set -ev

echo -e '<!-- Autogenerated by build.sh, do not edit! -->' > src/mathjaxheader.html
echo -e '<span class="math inline" style="display: none">\n\\(' >> src/mathjaxheader.html
cat mathsymbols.sty | sed  's/providecommand/renewcommand/g' >> src/mathjaxheader.html
echo -e '\\)\n</span>' >> src/mathjaxheader.html
# Rscript -e "bookdown::render_book('src/index.Rmd', 'bookdown::html_book')"
Rscript -e "bookdown::render_book('index.Rmd','bookdown::gitbook')"
Rscript -e "bookdown::render_book('index.Rmd','bookdown::pdf_book')"
# Rscript -e "bookdown::render_book('src/index.Rmd', 'bookdown::epub_book')"

