# Vells coneguts {#pilot}

Començarem recordant les definicions i resultats bàsics que ja s'han vist a altres
assignatures, com Fonaments o Estructures algebraiques. Donarem les definicions de cos,
característica, cos primer, i veurem que aquest és o bé $\FF_p$ per algun primer $p$, o bé $\QQ$.
A continuació introduïrem les extensions de cossos i el grau. Construirem el cos $F[x]/(p(x))$ associat
a un polinomi irreductible $p(x)\in F[x]$, i veurem alguns exemples.

## Convencions

En aquest curs, tots els anells seran commutatius, i assumirem sempre que tenen unitat. A més, demanarem
que un morfisme d'anells enviï l'$1$ a l'$1$.

## Característica d'un cos

Siguia $A$ un anell qualsevol. 
Considerem el morfisme $\iota\colon \ZZ\to A$ definit com:
$$
\iota(n)=\begin{cases}
1_A+1_A+\cdots+1_A & n \geq 0,\\
-(1_A+1_A+\cdots+1_A) & n < 0,
\end{cases}
$$
on les sumes tenen $n$ termes. És fàcil comprovar que és un morfisme. A més, fent
inducció en $\abs{n}$ es demostra fàcilment que $\iota$ és l'únic morfisme $\ZZ\to A$.
Per tant, a partir d'ara, qualsevol enter el podem pensar com a element d'un anell donat, i això no ens portarà
cap confusió.

Com ja sabem, el nucli d'un morfisme d'anells és un ideal. Per tant, el nucli del morfisme $\iota_A\colon \ZZ\to A$ és un ideal de $\ZZ$ de
la forma $(n)$, amb $n\geq 0$.

::: {.definition name="Característica"}
La *característica* d'un anell $A$ és l'enter no negatiu $n$ tal que $\iota_A = (n)$, i es denota per $\car(A)$.
:::

Fixem-nos que si $\car(A)=n$, aleshores $na = 0$ per a tot $a\in A$.

::: {.proposition #car-primer}
Sigui $F$ un cos. Aleshores la seva característica és $0$ o bé un primer $p$.
:::
::: {.proof}
Suposem que $\car(F)=n>0$, i $n=ab$. Aleshores $(a1_A)(b1_A)=(ab)1_A=0$. Com que $F$ és un cos,
això vol dir que $a1_A=0$ o $b1_A=0$. Si per exemple $a1_A=0$, això significa que $n \mid a$. Com que $n=ab$,
necessàriament $a=n$ i $b=1$. Per tant, els únics divisors de $n$ són trivials, i $n$ és primer.
:::

::: {.definition #cos-primer name="cos primer"}
El *cos primer* d'un cos $F$ és el cos generat per $1_F$. És o bé $\QQ$ (si $F$ té característica $0$) o bé el cos $\FF_p$
(si $F$ té característica $p$).
:::

## Extensions

Quan $K$ és un cos que conté un altre cos $F$, direm que $K$ és una *extensió* de $F$, i escriurem $K/F$ (no és cap mena de quocient!). Direm també que
$F$ és el *cos base* de l'extensió $K/F$. També farem servir
el diagrama
$$
\xymatrix{
  K\ar@{-}[d]\\
  F.
}
$$

Com que un cos no té ideals propis, un morfisme de cossos $\iota\colon F\to K$ és sempre injectiu i, per tant, la
imatge de $\iota$ és un subcos de $K$ isomorf a $F$. A partir d'ara, a vegades identificarem $F$ amb $\iota(F)$, i direm
que $K$ és una extensió de $F$.

Seguidament fem la següent observació clau: quan tenim una extensió $K/F$ aleshores $K$ esdevé automàticament un $F$-espai vectorial. Això
ens permet definir:

::: {.definition #grau-ext name="grau d'una extensió"}
El *grau* de l'extensió $K/F$ és la dimensió de $K$ com a $F$-espai vectorial, que escrivim com $[K\colon F]$. Direm que $K/F$ és finita si té grau finit,
i infinita si no.
:::

En un diagrama de cossos, sovint indicarem que l'extensió té grau $n$ així:
$$
\xymatrix{
  K\ar@{-}[d]_{n}\\
  F.
}
$$

::: {.theorem #kronecker name="Kronecker"}
Sigui $f(x)\in F[x]$ un polinomi. Aleshores existeix una extensió $K/F$ tal que $K$ té una arrel de $f(x)$.
:::
::: {.proof}
Considerem $K = F[x] / (g(x))$, on $g(x)$ és un factor irreductible qualsevol de $f(x)$. Sigui $\alpha$ la classe de $x$ a $K$. Aleshores $g(\alpha)=0$
i per tant $f(\alpha)=0$. Els elements de $K$ venen representats per $h(\alpha)$ on $h(x)\in F[x]$ són polinomis, que sempre
podem pensar de grau menor al grau de $g(x)$ (per la divisió euclídea). D'altra banda, el fet que $g(x)$ sigui irreductible
fa que $K$ sigui un cos. En efecte, si $h(\alpha)\neq 0$, tenim que $g(x) \nmid h(x)$ i per tant $g(x)$ i $h(x)$ són coprimers. Per la
identitat de Bézout, existeixen polinomis $a(x)$ i $b(x)$ tals que
$$
a(x)g(x)+b(x)h(x)=1,
$$
i per tant $b(\alpha)h(\alpha)=1$. És a dir, $h(\alpha)$ és invertible, amb invers $b(\alpha)$.
:::

El següent teorema ens diu que l'extensió donada pel teorema anterior té grau igual al grau del polinomi (per això s'ha triat
el nom!) quan aquest és irreductible. De fet, ens dona una base de $K$ com a $F$-espai vectorial.

::: {.theorem #ext-arrel-base}
Sigui $f(x)\in F[x]$ un polinomi irreductible de grau $n$, i sigui $K=F[x]/(f(x))$. Sigui $\alpha$ la classe de $x$ a $K$.
Aleshores els elements $\{1,\alpha,\ldots,\alpha^{n-1}\}$ formen una $F$-base de $K$.
:::
::: {.proof}
Tot element de $K$ té un representant de la forma $h(x)\in F[x]$. Dividint per $f(x)$, podem trobar un
representant equivalent però de grau $< n$. Per tant, els elements $\{1,\alpha,\ldots,\alpha^{n-1}\}$
generen $K$ com a $F$-espai vectorial. Cal veure que són linealment independents. Si hi hagués una
relació de dependència lineal, voldria dir que hi hauria un polinomi $g(x)\in F[x]$ de grau $< n$
tal que $g(\alpha)=0$. Però aleshores $g(x)$ hauria de ser un divisor de $f(x)$, que és impossible
ja que $f(x)$ és irreductible.
:::

L'aritmètica a $F[x]/(p(x))$ és molt explícita: els seus elements es poden expressar com a polinomis en $\alpha$ de grau
menor que $n=\deg(p(x))$. Donats dos polinomis $a(\alpha)$ per $b(\alpha)$, podem considerar
el residu $r(x)$ de dividir $a(x)b(x)$ per $p(x)$. Aleshores el producte $a(\alpha)b(\alpha)$ ve donat per l'element $r(\alpha)$.
Per divir ens cal utilitzar la identitat de Bézout (exercici).

::: {.example}
Potser l'exemple més conegut és el que s'obté de considerar el polinomi $x^2+1 \in \RR[x]$, que és irreductible perquè no té arrels. El
cos obtingut s'escriu $\CC$, i la classe de $x$ a $\RR[x]/(x^2+1)$ s'escriu $i$. Com que $i^2+1=0$, tenim $i^2=-1$ i recuperem les fórmules
habituals per treballar amb els nombres complexos.

De manera semblant, podem definir $\QQ[x]/(x^2+1)$ (adjuntem una arrel de $-1$ als racionals),  $\QQ[x]/(x^2-2)$ (adjuntem un element $\alpha$ amb $\alpha^2=2$),
o també $\QQ[x]/(x^3-2)$. Es poden fer les operacions habituals (suma, resta, multplicació, divisió) en algun d'aquests cossos de manera molt
explícita. Per exemple, $\QQ[x]/(x^2-2)$ està format,
com a conjunt, per tots els elements de la forma $a+b\alpha$, amb $a,b\in\QQ$. La multiplicació ve donada pel fet que $\alpha^2=2$.

De manera semblant, $\QQ[x]/(x^3-2) = \{a + b\beta + c\beta^2 ~|~ a,b,c\in\QQ \}$, i hem de recordar que $\beta^3=2$ per simplificar
el resultat de les multiplicacions.
:::

::: {.example}
Si considerem $\FF_p$ el cos finit de $p$ elements i un polinomi $f(x)\in \FF_p[x]$ irreductible de grau $n$
(suposant que existeixi!), aleshores obtenim un cos $K/\FF_p$ de grau $n$. Té, per tant, $p^n$ elements. Més endavant
veurem, d'una manera bastant indirecta, que per qualsevol primer $p$ i qualsevol enter $n\geq 1$ existeix un polinomi a $\FF_p[x]$
irreductible de grau $n$ (Proposició \@ref(prp:existencia-polis-irred-Fp))
:::

::: {.example}
També podem fer extensions de cossos més "exòtics". Per exemple, podem prendre $k(t)$ com el cos de funcions
racionals sobre un cos fixat $k$, i "afegir" una arrel quadrada de $t$ (mitjançant el polinomi $x^2-t$). Els seus elements
són de la forma $a(t)+b(t)\sqrt{t}$, on $a(t),b(t)\in k(t)$, i les operacions són les habituals.
:::

Una altra manera de crear nous cossos és definir-los com subextensions d'una extensió donada.
Sigui $K/F$ una extensió, i fixem un conjunt $S\subseteq K$. Aleshores podem considerar el "mínim" subcos $L\subseteq K$
que conté $F$ i tots els elements de $S$. S'anomena el *cos generat per $S$ sobre $F$*, i escriurem $F(S)$. Si $S$ és un
conjunt finit format per $\alpha_1,\ldots,\alpha_n$ aleshores escriurem $F(\alpha_1,\ldots,\alpha_n)$ i direm que
$F(S)$ és *finitament generat*. Un cas particular es dona
és quan $S$ conté un sol element: en aquest cas $F(\alpha)$ s'anomena una extensió *simple*, i l'element $\alpha$ s'anomena
un *element primitiu* de l'extensió (que no és únic, en general!).

::: {.theorem #ext-simple name="extensió simple"}
Sigui $f(x)\in F[x]$ un polinomi irreductible, i suposem que $K/F$ és una extensió
que conté una arrel $\alpha$ de $f(x)$.
Aleshores hi ha un isomorfisme $$F[x]/(f(x))\cong F(\alpha).$$
Aquest isomorfisme és únic si demanem que $[x]\mapsto \alpha$.
:::
::: {.proof}
Tenim
\begin{align*}
\Hom_F(F[x]/(f(x)), F(\alpha)) &\cong \{ \varphi \in \Hom_{F}(F[x], F(\alpha)) ~|~ \varphi(f) = 0\}\\
& \cong \{\beta\in F(\alpha) ~|~ f(\beta)=0\}\neq\emptyset.
\end{align*}
Donat un morfisme $\varphi$, és automàticament un isomorfisme, fet que comprovem calculant graus de les extensions.
:::

::: {.example}
El cos $\QQ(\sqrt{2})\subset \RR$ és isomorf a $\QQ[x]/(x^2-2)$. Hi ha dos isomorfismes possibles, l'un identifica $[x]\leftrightarrow \sqrt{2}$
i l'altre $[x]\leftrightarrow -\sqrt{2}$.

Considerem ara $\QQ(\sqrt[3]{2}) \subset \RR$. Aquest cos també és isomorf a $\QQ[x]/(x^3-2)$, però aquesta vegada només hi ha un isomorfisme
possible, el que assigna $[x]\leftrightarrow \sqrt[3]{2}$. Això és així perquè el polinomi $x^3-2$ només té una arrel real. També hi ha un
subcòs de $\CC$ que és isomorf a $\QQ[x]/(x^3-2)$, que és el generat per $\zeta_3\sqrt[3]{2}$, on $\zeta_3=\frac{-1+i\sqrt{3}}{2}$ és una
arrel cúbica de la unitat. Hi ha dos isomorfismes possibles, de fet, el que identifica $[x]\leftrightarrow \zeta_3\sqrt[3]{2}$ i el que
identifica $[x]\leftrightarrow \zeta_3^{-1}\sqrt[3]{2}$.
:::

::: {.remark}
En els exemples, hem construit cossos que contenen una de les tres possibles arrels de $x^3-2$. Aquests són isomorfs, tal
i com hem vist. El fet que un sigui subcos de $\RR$ i l'altre de $\CC$ té a veure amb anàlisi, no amb àlgebra. Algebraicament,
no es poden distingir. 
:::

Acabem amb un teorema que ens servirà més endavant. Ens anirà bé fer servir la notació següent. Si
$\sigma \colon F \to L$ és un morfisme de cossos i $f(x)\in F[x]$ és un polinomi qualsevol,
escrivim $\sigma(f)\in L[x]$ per denotar el polinomi obtingut d'$f(x)$ aplicant $\sigma$ als seus
coeficients.

::: {.theorem #extensio-morfismes name="extensió de morfismes"}
Sigui $\sigma\colon F\to L$ un morfisme de cossos.
Sigui $f(x)\in F[x]$ un polinomi irreductible. Aleshores l'aplicació $\varphi \mapsto \varphi(\alpha)$ indueix una bijecció
$$
\Hom_{\sigma}(F(\alpha), L) \stackrel{\cong}{\to} \{\beta\in L ~|~ \sigma(f)(\beta) = 0 \}.
$$
$$
\xymatrix{
  F(\alpha)\ar@{-->}^{\varphi}[r]\ar@{-}[d] & L\\
  F\ar^{\sigma}[ur].
}
$$
:::
::: {.proof}
$$
\Hom_\sigma (F(\alpha), L) \cong \Hom_{\sigma}(F[x]/(f(x)), L) \cong \{ \varphi \in \Hom_{\sigma}(F[x],L) ~|~ \varphi(f) = 0\},
$$
i aquest últim conjunt és precisament $\{\beta \in L ~|~ \sigma(f)(\beta) = 0\}$.
:::
