# Galois entre els radicals {#pilot}

Parlem de les equacions polinomials en una variable, la famosa fórmula quadràtica i els monstres de grau tres i quatre.

En aquests casos, les solucions es poden expressar en termes de les quatre operacions bàsiques a més de l'extracció d'arrels.

Seguidament, estudiem el polinomi $x^3-2$, que té una arrel real i dues de complexes. Les podem dibuixar al pla, formen un triangle equilàter. Aquest triangle té un grup de simetries, que és el grup diedral $D_{2\times 3}$ que ja s'ha estudiat a l'assignatura Estructures Algebraiques. D'altra banda, podem introduir el subcòs de $\CC$ anomenat $\QQ(\alpha,\omega)$ on $\alpha=\sqrt[3]{2}$ i $\omega=e^{2\pi i /3}$ és una arrel cúbica primitiva de la unitat. Aquest és el mínim cos que conté totes les arrels del nostre polinomi (exercici). Ara podem definir les "simetries" d'aquest cos com el grup dels automorfismes (morfismes de cossos que són invertibles, encara que aquesta segona condició serà bastant supèrflua).

Seguidament, canviem el polinomi d'estudi a $x^5-2$. Aquí hi ha 10 simetries geomètriques, però en canvi hi ha moltes més "simetries" com a cos de les arrels. En aquest cas, en tenim 20 (en general, si $p$ és un primer, $x^p-2$ té $p(p-1)$ simetries en les arrels, però només $2p$ simetries geomètriques.

L'objectiu de la Teoria de Galois és estudiar aquest nou grup de simetries, que ens dona molta informació sobre les arrels. En particular, aquest grup ens determina la resolubilitat per radicals del polinomi en qüestió.
