# Torres

Definirem elements algebraics i transcendents i el polinomi mínim d'un element algebraic, amb exemples.
Enunciarem i demostrarem la fórmula de les torres, i com es comporta el grau en composicions de cossos.

## Extensions algebraiques/transcendents

Considerem una extensió $K/F$.

::: {.definition name="element algebraic"}
Diem que un element $\alpha\in K$ és *algebraic sobre $F$* si $\alpha$ és l'arrel d'un polinomi $f(x)\in F[x]$.

Diem que $\alpha$ és *transcendent sobre $F$* si no és algebraic.

L'extensió $K/F$ és *algebraica* si tots els elements $\alpha\in K$ són algebraics sobre $F$.
:::

Fixem-nos que si $\alpha$ és algebraic sobre $F$ aleshores sabem que hi ha *algun* polinomi $f(x)\in F[x]$ que té $\alpha$
com a arrel. Però n'hi ha molts més, per exemple qualsevol múltiple de $f(x)$. El següent resultat ens permet assignar un
polinomi *canònic* a cada element algebraic.

::: {.proposition}
Si $\alpha$ és algebraic sobre $F$, aleshores hi ha un únic polinomi **mònic** i **irreductible** $\Irr_{\alpha,F}(x)$ que
té $\alpha$ com a arrel. A més, $f(x)\in F[x]$ té $\alpha$ com a arrel si i només si és un múltiple de $\Irr_{\alpha, F}(x)$.
:::
::: {.proof}
Sigui $g(x)\in F[x]$ un polinomi mònic amb $\alpha$ com a arrel, i amb grau mínim entre tots ells. Si es pogués
trencar com $g(x)=g_1(x)g_2(x)$, aleshores $\alpha$ seria una arrel d'un dels $g_i(x)$, contradient la minimalitat
del grau de $g(x)$.

Suposem que $f(x)$ satisfà $f(\alpha)=0$. Dividint per $\Irr_{\alpha,F}(x)$, tenim
$$
f(x)=\Irr_{\alpha,F}(x) q(x)+r(x),
$$
i substituint a $x=\alpha$ tindrem $r(\alpha)=0$. Per minimalitat, deduïm que $r(x)=0$, com volíem.
:::

Fixem-nos que, si $K/L/F$ és una torre d'extensions i $\alpha\in K$ és algebraic sobre $F$, aleshores també ho és sobre $L$,
i a més $\Irr_{\alpha,L}(x)$ divideix $\Irr_{\alpha,F}(x)$ a $L[x]$.

::: {.definition name="polinomi mínim"}
El polinomi $\Irr_{\alpha,F}(x)$ s'anomena el *polinomi mínim d'$\alpha$ sobre $F$*, i el seu grau s'anomena el *grau d'$\alpha$*
sobre $F$.
:::

Posant junt tot el què hem vist fins ara, si prenem $\alpha\in K$ aleshores podem considerar la subextensió
$F(\alpha)/F$.
En aquest cas, $F(\alpha)\cong F[x]/(\Irr_{\alpha,F}(x))$ i per tant $[F(\alpha)\colon F] = \deg \alpha$.

::: {.example}
El polinomi mínim de $\sqrt{2}\in \RR$ sobre $\QQ$ és $x^2-2$. Diem que $\sqrt{2}$ és un element *quadràtic* sobre $\QQ$. De manera
semblant, el polinomi mínim de $\sqrt[3]{2}$ és $x^3-2$. Aquests dos polinomis són irreductibles sobre $\QQ$ per exemple per que són
$2$-Eisenstein.
:::

::: {.proposition}
Si $[K\colon F]=n$ i $\alpha\in K$, aleshores $\deg\alpha\leq n$. En particular, tota extensió finita $K/F$ és algebraica.
:::
::: {.proof}
Considerem els elements $1, \alpha, \alpha^2,\ldots, \alpha^{n-1}, \alpha^{n}$. Com que n'hi ha $n+1$, hi ha
d'haver una relació de dependència lineal entre ells, i això ens dona un polinomi $f(x)\in F[x]$ de grau $\leq n$ tal que $f(\alpha)=0$.
:::

No és cert que tota extensió algebraica sigui finita (en veurem exemples més endavant).

El següent resultat ens caracteritza com són les extensions quadràtiques d'un cos $F$ de característica $\neq 2$.

::: {.proposition}
Sigui $F$ un cos de característica $\neq 2$, i sigui $K/F$ una extensió de grau $2$. Aleshores existeix $\delta\in K\setminus F$
tal que $\delta^2=D\in F$ i $K=F(\delta)$. Escriurem que $K=F(\sqrt{D})$.
:::
::: {.proof}
Prenem $\alpha\in K\smallsetminus F$. Per tant, $\alpha$ satisfà un polinomi de grau dos, que podem suposar
mònic, posem $f(x)=x^2 + bx+c$ amb $b,c\in F$. Observem que $F(\alpha)=K$, ja que $F(\alpha)$ és una extensió
de grau $2$ dins de $K$. Sigui $\delta=\alpha+b/2$. Aleshores és fàcil veure que $\delta$ és una arrel del
polinomi $g(x)=x^2-D$, on $D=b^2-4c$. Per tant, $F(\alpha)=F(\delta)=F(\sqrt{D})$.
:::

## Torres de cossos

En aquesta secció considerem torres $L/K/F$. Ens interessa relacionar les dues extensions $L/K$ i $K/F$ amb l'extensió
total $L/F$.

::: {.proposition}
Sigui $K/F$ una extensió, i sigui $V$ un $K$-espai vectorial. Aleshores
$$
\dim_F V = [K\colon F] \dim_K V.
$$
:::
::: {.proof}
Sigui $\{v_i\}_{i\in I}$ una $K$-base de $V$, i sigui $\{\alpha_j\}_{j\in J}$ una base de $K$ sobre $F$.
Aleshores és fàcil comprovar que el conjunt $\{\alpha_j v_i\}_{i\in I, j \in J}$ forma una $F$-base de $V$.
:::

::: {.theorem #torres name="fórmula de les torres"}
Si $F\subseteq K\subseteq L$, aleshores
$$
[L\colon F] = [L \colon K] [K \colon F].
$$
Si un costat de l'equació és infinit, aleshores l'altre també.
:::
::: {.proof}
Es dedueix directament del lema anterior.
:::

::: {.corollary}
Si $L/F$ és una extensió finita i $K/F$ és una subextensió (és a dir, $K\subseteq L$) aleshores $[K\colon F]$ divideix $[L\colon F]$.
:::

Per exemple, el corol·lari anterior ens permet deduïr que $\sqrt{2}$ no pertany a cap extensió de grau senar.

::: {.exercise}
Demostreu que el polomi $x^3-\sqrt{2}$ és irreductible sobre $\QQ(\sqrt{2})$, fent servir la torre $\QQ(\sqrt[6]{2}) / \QQ(\sqrt{2}) / \QQ$.
:::

El següent lema senzill ens permetrà construir qualsevol extensió finitament generada de manera iterativa:

::: {.lemma}
Si $\alpha$ i $\beta$ són elements de $K/F$, aleshores $F(\alpha,\beta)=(F(\alpha))(\beta)$.
:::
::: {.proof}
El cos $F(\alpha,\beta)$ conté $F(\alpha)$. Com que també conté $\beta$, tenim $F(\alpha)(\beta)\subseteq F(\alpha,\beta)$
per minimalitat de $F(\alpha)(\beta)$.

Recíprocament, com que el cos $F(\alpha)(\beta)$ conté a $F$, a $\alpha$ i a $\beta$, aleshores per minimalitat de $F(\alpha,\beta)$
tenim que $F(\alpha,\beta)\subseteq F(\alpha)(\beta)$.
:::

::: {.exercise}
Calculeu el grau de l'extensió $\QQ(\sqrt{2},\sqrt{3})/\QQ$, i doneu-ne una base.
:::

::: {.theorem}
L'extensió $K/F$ és finita si i només si $K=F(S)$ on $S$ és un conjunt finit d'elements algebraics.
:::
::: {.proof}
Suposem $K/F$ finita de grau $n$, i sigui $S$ el conjunt (finit) format per una base de $K$ sobre $F$. Aleshores
$K=F(S)$, i els
elements $\alpha\in S$ són tots algebraics, ja que $[F(\alpha)\colon F]$ divideix $n$ i en particular el grau
és finit.

Recíprocament, si $K=F(S)$ amb $S$ un conjunt finit d'elements algebraics, aleshores podem obtenir $K$ adjuntant
successivament els elements de $S$, i cada extensió és finita.
:::

::: {.corollary}
Si $\alpha$ i $\beta$ són algebraics sobre $F$, aleshores també ho són $\alpha\pm \beta$, $\alpha\beta$ i $\alpha/\beta$ (si $\beta\neq 0$).
:::

::: {.corollary}
Si $L/F$ és una extensió qualsevol, aleshores el conjunt $K$ d'elements de $L$ que són algebraics sobre $F$ forma un subcos $L/K/F$.
:::

Per exemple, podem considerar $\bar{\QQ}\subseteq\CC$, el conjunt de tots els complexos algebraics, o també $\bar{\QQ}\cap \RR$, el conjunt
dels reals algebraics. Aquests cossos són enumerables (tenen un conjunt d'elements enumerable) i per tant són més petits que $\RR$ i que $\CC$.
D'aquest fet obtenim que hi ha (molts) elements de $\RR$ que no són algebraics. En canvi, sovint és difícil demostrar que
un real donat (per exemple $\pi$) és transcendent.

::: {.theorem}
Si $K/F$ és una extensió algebraica i $L/K$ també, aleshores $L/F$ és algebraica.
:::
::: {.proof}
Sigui $\alpha\in L$. Per tant, $\alpha$ satisfà un polinomi $f(x)\in K[x]$. Sigui $S$ el conjunt (finit)
format pels coeficients de $f(x)$. Com que $K/F$ és algebraica, els elements de $S$ són tots algebraics
i per tant l'extensió $F(S)/F$ és finita. Considerem el cos $F(\alpha,S)$. Tenim:
$$
[F(\alpha,S)\colon F] = [F(\alpha,S)\colon F(S)] [F(S) \colon F].
$$
El primer terme és menor o igual que el grau del polinomi $f(x)$, ja que podem pensar $f(x)\in F(S)$ i
$\alpha$ n'és una arrel. El segon terme és finit, com hem dit. Per tant $F(\alpha,S)$ és una extensió
finita, i això vol dir que $\alpha$ és algebraic sobre $F$.
:::


## Compositum de cossos

Recordem que donats dos cossos $K_1/F$ i $K_2/F$, el seu *compost* (o *compositum*) $K_1K_2 /F$ és el mínim cos que conté
tant a $K_1$ com a $K_2$. També es pot pensar com la intersecció de tots els cossos $L/F$ que contenen el conjunt $K_1\cup K_2$.

::: {.proposition}
Siguin $K_1/F$ i $K_2/F$ dues extensions contingudes a $K$. Aleshores
$$
[K_1K_2\colon F] \leq [K_1\colon F] [K_2 \colon F].
$$
La igualtat es dona si i només si una base de $K_1/F$ segueix essent linealment independent sobre $K_2$ (o a
l'inrevés). A més, tenim:
$$
\xymatrix{
  & K_1 K_2 \\
  K_1\ar@{-}^{\leq m}[ur]\ar@{-}^{n}[dr] &&K_2\ar@{-}[ul]_{\leq n}\ar@{-}[dl]^{m}\\
  &F
}
$$
:::
::: {.proof}
Cal veure que els productes $\alpha\beta$ on $\alpha$ i $\beta$ recorren bases respectives de $K_1/F$ i de $K_2/F$
generen $K_1K_2/F$. N'hi ha prou amb veure que les combinacions lineal d'aquests elements formen un cos, que és
una observació senzilla.
:::

Fixem-nos que, si $m$ i $n$ són coprimers, aleshores per la fórmula de les torres tenim $[K_1K2\colon K_1]=m$ i $[K_1K_2\colon K_2]=n$.
En general, però les desigualtats del diagrama anterior seran estrictes.


