# Polinomis (In)separables

Definim la noció de separabilitat d'un polinomi, i posem algun exemple. Introduïm el morfisme de Frobenius,
que ens permet definir cossos perfectes. Aprofitem per parlar del grau de separabilitat/inseparabilitat d'una
extensió, i la factorització d'aquesta.

Finalment, donem l'existència i unicitat dels cossos finits, i estudiem els polinomis ciclotòmics.

## Separabilitat de polinomis i extensions

Sigui $F$ un cos.

::: {.definition #separabilitat name="separabilitat"}
Un polinomi $f(x)\in F[x]$ és *separable* si les seves arrels (en un cos de descomposició) són totes diferents. Si $f(x)$
no és separable diem que $f(x)$ és *inseparable*.
:::

Fixem-nos que la definició no depèn del cos de descomposició que ens triem, per unicitat llevat d'isomorfisme. De fet, podem
caracteritzar la separabilitat de $f(x)$ sense haver de considerar cap cos de descomposició:

::: {.proposition #separabilitat-iff-coprimer-derivada}
Un polinomi $f(x)$ té una arrel múltiple $\alpha$ si i només si $\alpha$ és una arrel de $f'(x)$. En particular, $f(x)$
és separable si i només si $\mcd(f(x), f'(x)) = 1$.
:::
::: {.proof}
Si $f(x)=(x-\alpha) g(x)$, aleshores $f'(x) = g(x) + (x-\alpha)g'(x)$ i, per tant, $f'(\alpha)=0$ si i només si $g(\alpha)=0$,
si i només si $f(x)=(x-\alpha)^2h(x)$.
:::
::: {.corollary}
Si $f(x)\in F[x]$ és irreductible i $F$ té característica $0$, aleshores $f$ és separable. En general,
un polinomi $f(x)\in F[x]$ és separable si i només si és producte de diferents polinomis irreductibles.
:::
::: {.proof}
Si $f(x)$ té una arrel múltiple $\alpha$, aleshores $h(x)=\mcd(f(x),f'(x))$ és un múltiple de $(x-\alpha)$ que divideix $f(x)$,
i per tant $f(x)$ no pot ser irreductible.
:::

::: {.example}
El polinomi $x^n-1$ té derivada $nx^{n-1}$ i per tant, si $n\neq 0$ a $F$ aleshores $x^n-1$ és separable, i en aquest cas hi ha $n$
arrels de la unitat diferents a $F$. En canvi, si $F$ és de característica $p\mid n$, aleshores cada arrel de $x^n-1$ és múltiple.
:::

Ja hem estudiat el problema de separabilitat en característica $0$, que és molt senzill. Ens centrarem ara en característica $p$, així que
sigui $F$ un cos de característica finita $p$. Pensem en què pot anar malament per tal que un polinomi irreductible $f(x)\in F[x]$ sigui inseparable. Cal que la seva derivada
tingui factors en comú amb $f(x)$, i això només pot passar si la derivada és $0$.

::: {.lemma}
Sigui $f(x)\in F[x]$ amb  $\car(F)=p$. Si $f'(x)=0$, aleshores hi ha un polinomi $f_1[x]\in F[x]$ tal que $f(x)=f_1(x^p)$.
:::

En particular, observem que si $f(x)\in F[x]$ és inseparable, aleshores el seu grau és un múltiple de $p$.

::: {.proposition}
Sigui $f(x)\in F[x]$ amb $\car(F)=p$ un polinomi irreductible. Aleshores hi ha un únic $k\geq 0$ i un únic
polinomi irreductible i separable $g(x)\in F[x]$ tal que
$$
f(x)=g(x^{p^k}).
$$
:::
::: {.proof}
Iterem el procediment del lema anterior fins que el polinomi que obtenim és separable. Seguirà essent
irreductible, i ja haurem acabat.
:::

::: {.definition #grau-separabilitat name="grau de separabilitat"}
Sigui $f(x)\in F[x]$ amb $\car(F)=p$ un polinomi irreductible. El *grau de separabilitat* de $f(x)$
és el grau de $g(x)$ en la proposició anterior, i el denotem per $\deg_s f(x)$.

El *grau d'inseparabilitat* és l'enter $p^k$ que hi apareix, i el denotem per $\deg_i f(x)$.
:::

Observem que $\deg f(x) = \deg_s f(x) \deg_i f(x)$.

::: {.proposition #frobenius}
Sigui $F$ un cos de característica $p$. Aleshores l'aplicació $a \mapsto a^p$ és un morfisme de cossos $F\to F$.
:::
::: {.proof}
Només cal veure que $(a+b)^p = a^p + b^p$ i que $(ab)^p = a^p b^p$. La primera igualtat es veu fent servir que $p$ divideix a $\binom{p}{i}$
per a $1\leq i\leq p-1$, i la segona és trivial.
:::

El morfisme de la proposició anterior s'anomena el *morfisme de Frobenius*. Observem que si $\FF$ és un cos finit, aleshores el morfisme de
Frobenius és un isomorfisme (només cal comptar), però en general no és cert.
Per exemple, la imatge de Frobenius a $F=\FF_p(t)$ és $\FF_p(t^p)$.

::: {.proposition}
Sigui $\FF$ és un cos de característica $p$ tal que el morfisme
de Frobenius és exhaustiu. Aleshores tot polinomi irreductible sobre $\FF$ és separable.
:::
::: {.proof}
Suposem que $f(x)$ fos inseparable. Aleshores $f(x)=f_1(x^p)$ per algun $f_1(x)\in \FF[x]$. Els coeficients de $f_1$ són potències de $p$, i
aleshores podem escriure
$$f_1(x)=a_m^px^m+a_{m-1}^px^{m-1}+\cdots a_1^px + a_0^p.$$

Per tant, tenim
$$
f(x)=f_1(x^p) = a_m^px^{pm}+a_{m-1}^px^{p(m-1)}+\cdots a_1^px^p + a_0^p = \left(a_mx^m+a_{m-1}x^{m-1}+\cdots a_1x + a_0\right)^p,
$$
que contradiu el fet que $f(x)$ sigui irreductible.
:::

Aquesta definició ens servirà per unificar els dos casos on la separabilitat no és problemàtica.

::: {.definition #cos-perfecte name="cos perfecte"}
Un cos $F$ és *perfecte* si té característica $0$ o bé el morfisme de Frobenius és exhaustiu.
:::

::: {.corollary}
Si $F$ és perfecte, aleshores tot polinomi irreductible a $F[x]$ és separable.
:::


Finalment, podem introduir el concepte d'extensió separable.

::: {.definition #ext-separable name="extensió separable"}
Una extensió $K/F$ és *separable* si tot element de $K$ és arrel d'un polinomi separable sobre $F$.
:::
::: {.corollary}
Tota extensió finita d'un cos perfecte és separable. En particular, els cossos finits són separables.
:::

::: {.corollary}
Sigui $F$ un cos de característica $p$, i sigui $K/F$ una extensió finita tal que $p \nmid [K\colon F]$.
Aleshores $K/F$ és separable.
:::
::: {.proof}
Sigui $\alpha \in K$, i considerem $\Irr_{\alpha, F}(x)$. Com que el seu grau és un divisor de $[K\colon F]$,
no pot ser divisible per $p$ i, per tant, és separable.
:::

Més endavant ens serà útil saber que que la separabilitat es comporta bé en torres.
::: {.lemma}
Sigui $L/K/F$ una torre. Si $L/F$ és separable, aleshores $L/K$ i $K/F$ també ho són.
:::
::: {.proof}
Si $L/F$ aleshores $K/F$ és separable, trivialment. Per veure que $L/K$ també ho és, observem
simplement que per tot $\alpha\in L$, el polinomi $\Irr_{\alpha,K}(x)$ és un divisor (a $K[x]$) del polinomi $\Irr_{\alpha,F}(x)$.
:::

Més endavant veurem que el recíproc també és cert, però per ara no ens caldrà.


## Polinomis Ciclotòmics {#ciclotomics}

L'objectiu principal és demostrar que l'extensió ciclotòmica $\QQ(\zeta_n)$ té grau $\varphi(n)$ (la phi d'Euler). Per això,
introduïrem els polinomis ciclotòmics, veurem que són irreductibles i mònics i tenen coeficients enters.

Sigui $\mu_n$ el grup de les arrels $n$-èssimes de la unitat, que podem pensar dins de $\CC$.
Com a grup abstracte, és isomorf a $\ZZ/n\ZZ$ (un cop fixem una arrel primitiva $\zeta_n$):
$$
\ZZ/n\ZZ \to \mu_n,\quad a \mapsto \zeta_n^a.
$$
Ja hem observat que les arrels primitives són exactament les de la forma $\zeta_n^a$ amb $a$ coprimer amb $n$
i que, per tant, n'hi ha $\varphi(n)$. Fixem-nos també que si $d\mid n$ aleshores $\mu_d \subseteq \mu_n$.
Però fixem-nos que si $\zeta\in \mu_n$, aleshores $\zeta$ és una arrel primitiva $d$-èssima per algun $d \mid n$.

::: {.definition #polinomi-ciclotomic name="polinomi ciclotòmic"}
El *polinomi ciclotòmic $n$-èssim* $\Phi_n(x)$ és el polinomi de grau $\varphi(n)$ que té per arrels
les arrels primitives de la unitat:
$$
\Phi_n(x) = \prod_{\substack{1\leq a \leq n\\\mcd(a,n)=1}} (x-\zeta_n^a).
$$
:::

Tenim la factorització
$$
x^n - 1= \prod_{\zeta \in \mu_n} (x-\zeta) = \prod_{d\mid n} \Phi_d(x).
$$
En particular, comparant graus tenim la identitat
$$
n = \sum_{d \mid n} \varphi(d).
$$


A més, fixem-nos que la fórmula anterior ens permet calcular els polinomis ciclotòmics de manera recursiva,
dividint pels factors coneguts:
\begin{equation}
\Phi_n(x) = \frac{x^n - 1}{\displaystyle\prod_{\substack{d \mid n\\d < n}} \Phi_d(x)}.
(\#eq:ciclotomics-recursius)
\end{equation}


Els primers valors són, per exemple:

\begin{align*}
\Phi_1(x) &= x-1&\Phi_2(x) &= x+1\\
\Phi_{3}(x) &= x^{2} + x + 1 &\Phi_{4}(x) &= x^{2} + 1 \\
\Phi_{5}(x) &= x^{4} + x^{3} + x^{2} + x + 1 &\Phi_{6}(x) &= x^{2} - x + 1 \\
\Phi_{7}(x) &= x^{6} + x^{5} + x^{4} + x^{3} + x^{2} + x + 1 & \Phi_{8}(x) &= x^{4} + 1 \\
\Phi_{9}(x) &= x^{6} + x^{3} + 1 & \Phi_{10}(x) &= x^{4} - x^{3} + x^{2} - x + 1
\end{align*}

::: {.lemma}
Els polinomis $\Phi_n(x)$ són mònics de grau $\varphi(n)$ i tenen coeficients enters.
:::
::: {.proof}
L'únic que ens cal veure és que $\Phi_n(x)$ té coeficients enters. Això es veu fàcilment per inducció en $n$
i l'algoritme de divisió, fent servir la fórmula \@ref(eq:ciclotomics-recursius).
:::

Amb una mica més de feina podem veure que també són irreductibles.

::: {.theorem #ciclotomics-irreductibles}
Els polinomis $\Phi_n(x)$ són irreductibles.
:::
::: {.proof}
Prenem $n\geq 3$, i escrivim una factorització $\Phi_n(x)=f(x)g(x)$ amb $f(x)$ i $g(x)$ mònics a $\ZZ[x]$, i amb $f(x)$
irreductible de grau com a mínim $2$. L'objectiu és demostrar que $f(x)=\Phi_n(x)$, és a dir, que tota arrel primitiva $n$-èssima
és arrel de $f(x)$. Sigui doncs $\zeta$ una arrel $n$-èssima primitiva que sigui arrel de $f(x)$, i veurem
que $\zeta^a$ també és arrel de $f(x)$ per a tot $a$ coprimer amb $n$. N'hi ha prou amb veure-ho per $a=p$ un primer no dividint $n$,
perquè aleshores podem iterar l'argument.

Com que $\zeta^p$ és una arrel primitiva de la unitat, ha de ser una arrel de $f(x)$ o de $g(x)$. Si $g(\zeta^p)=0$, aleshores $\zeta$
és una arrel de $g(x^p)$. Per tant, a $\ZZ[x]$ tenim
$$
g(x^p) = f(x)h(x).
$$
Reduïnt mòdul $p$ i fent servir el "Freshman's dream", tenim
$$
(\bar{g}(x))^p = \bar{f}(x)\bar{h}(x) \text{ a } \FF_p[x].
$$
D'aquí en deduïm que $\bar{f}(x)$ i $\bar{g}(x)$ tenen un factor comú a $\FF_p[x]$. Per tant, $\bar{\Phi}_n(x)=\bar{f}(x)\bar{g}(x)$ té un
factor repetit, i com que $\Phi_n(x)$ divideix $x^n-1$, també $x^n-1$ té un factor repetit a $\FF_p[x]$. Però ja hem vist que aquest
polinomi no té factors repetits, i per tant tenim una contradicció.
:::

::: {.corollary}
El cos ciclotòmic $\QQ(\zeta_n)$ té grau $\varphi(n)$ sobre $\QQ$.
:::