# Clausures algebraiques

En aquest episodi demostrem l'existència i unicitat de la clausura algebraica d'un cos.

## Conceptes bàsics

En aquesta secció definirem la noció de clausura algebraica d'un cos arbitrari.

::: {.definition #clausura-algebraica name="clausura algebraica"}
Diem que $\bar{F}/F$ és una *clausura algebraica* d'$F$ si $\bar{F}/F$ és algebraica i tot polinomi $f(x)\in F[x]$
descomposa completament a $\bar{F}$.
:::

::: {.definition #algebraicament-tancat name="algebraicament tancat"}
Un cos $F$ és *algebraicament tancat* si és una clausura algebraica sobre si mateix. És a dir, si tot
polinomi $f(x)\in F[x]$ té alguna arrel a $F$.
:::

Aviat veurem que tot cos té alguna clausura algebraica, i que hi ha cossos algebraicament tancats. Veurem
primer que les clausures algebraiques són algebraicament tancades.

::: {.proposition #clausura-tancada}
Sigui $\bar{F}/F$ una clausura algebraica de $F$. Aleshores $\bar{F}$ és algebricament tancat.
:::
::: {.proof}
Considerem un polinomi $f(x)\in \bar{F}[x]$, i considerem l'extensió $\bar{F}(\alpha)$ obtinguda adjuntant
una arrel de $f(x)$ a $\bar{F}$. Aleshores $\bar{F}(\alpha)/\bar{F}/ F$ és una torre algebraica, i per tant
l'extensió total és algebraica. En particular, $\alpha$ és algebraic sobre $F$ i, per tant, $\alpha \in \bar{F}$,
com volíem demostrar.
:::

El següent resultat ens permet trobar una clausura algebraica de qualsevol subcos d'un cos algebraicament tancat.

::: {.proposition #clausura-tecnica}
Sigui $K/F$ una extensió, i suposem que $K$ és algebraicament tancada. Aleshores la subextensió $\bar{F}/F$
formada pels elements de $K$ que són algebraics sobre $F$ és una clausura algebraica de $F$ .
:::
::: {.proof}
L'extensió $\bar{F} / F$  és algebraica per definició. Donat un polinomi
$f(x)\in F[x]$, aquest trencarà completament a $K$ en producte de polinomis de la forma $x-\alpha$. Però
cadascun dels $\alpha$ és algebraic sobre $F$ i, per tant, és un element de $\bar{F}$. Per tant $f(x)$ ja trencava
completament a $\bar{F}[x]$, i per tant $\bar{F}$ és una clausura algebraica de $F$.
:::

Cap al final del curs veurem una demostració del següent teorema com a aplicació de diversos resultats de Teoria de Galois. Hi ha
altres demostracions (potser més naturals) fent servir mètodes analítics.

::: {.theorem #fta name="Teorema Fonamental de l'Àlgebra"}
El cos $\CC$ dels nombres complexos és algebraicament tancat
:::

Com a conseqüència, podrem clausures algebraiques de qualsevol extensió subextensió $\CC/F/\QQ$. En particular,
el cos $\QQbar$ format pels complexos algebraics és una clausura algebraica de $\QQ$.

## Cossos finits

L'objectiu és demostrar l'existència de cossos finits d'ordre qualsevol potència d'un primer, i veure que són únics
(llevat d'isomorfisme). També veurem que existeix la clausura algebraica de qualsevol cos finit.

::: {.theorem name="Existència i unicitat de cossos finits"}
Per tot primer $p$ i tot $n\geq 1$, hi ha un únic (llevat d'isomorfisme) cos finit d'ordre $p^n$, que
denotarem per $\FF_{p^n}$. A més, tot cos finit de característica
$p$ és isomorf a $\FF_{p^n}$ per alguna $n \geq 1$.
:::

::: {.proof}
Sigui $n\geq 1$, i fixem-nos que el polinomi $f(x)=x^{p^n}-x \in \FF_p[x]$ té derivada $-1$ i, per tant, és separable.
Si $\alpha$ i $\beta$ són dues arrels qualssevol, aleshores $\alpha\beta$ i $\alpha+\beta$
també són arrels. Per tant, el conjunt $L$ format per les $p^n$ arrels forma un subcos del cos de
descomposició de $f(x)$ i, per tant, com que $L$ conté totes les arrels, ha de ser el propi
cos de descomposició. Com que $L$ té $p^n$ elements, té grau $n$ sobre $\FF_p$, i per tant hem
vist que hi ha cossos finits de grau $n$ per qualsevol $n\geq 1$.

Sigui ara $\FF$ un cos finit qualsevol de característica $p$. Com que és un espai vectorial sobre el seu
cos primer $\FF_p$, ha de tenir $p^n$ elements per algun $n\geq 1$. Fixem-nos que $\FF^\times$ és un grup
d'ordre $p^n-1$ i, per tant $\alpha^{p^n-1} = 1$ per tot $\alpha\in \FF$. Per tant $\alpha$ és una arrel
de $x^{p^n}-x$ i $\FF$ està contingut al cos de descomposició d'aquest polinomi. Mirant el nombre
d'elements, veiem que és igual al cos de descomposició.
:::

Fixem-nos que encara no hem sabut demostrar que existeixen polinomis irreductibles a $\FF_p[x]$ de qualsevol grau. El que
ens caldria és demostrar que l'extensió $\FF_{p^n}/\FF_p$ és *simple*, és a dir, que s'obté adjuntant l'arrel d'un polinomi
irreductible. Això ho veurem més endavant, a la Proposició \@ref(prp:existencia-polis-irred-Fp).

Fixem-nos que tenim una cadena d'inclusions
$$
\FF_p\subset \FF_{p^2} \subset \FF_{p^{6}} \subset \FF_{p^{4!}} \subset \cdots \subset \FF_{p^{n!}} \subset\cdots,
$$
i podem considerar el cos $\Fpbar = \bigcup_{n\geq 1} \FF_{p^{n!}}$ (és fàcil veure que és un cos).

::: {.proposition}
El cos $\Fpbar$ és una clausura algebraica d'$\FF_p$.
:::
::: {.proof}
Primer, observem que $\FF_{p^{n!}}$ conté $\FF_{p^n}$ per a tot $n$, i per tant també $\Fpbar$ conté tots els cossos finits. Donat
un polinomi $f(x)\in \Fpbar[x]$, els seus coeficients viuen tots en un cert cos $\FF_{p^{n!}}$ i per tant el cos de descomposició
d'aquest polinomi és una certa extensió finita d'aquest, i està contingut a $\Fpbar$. Ara bé, com que tots els $\FF_{p^{n!}}$ són
cossos de descomposició i $\Fpbar$ és el mínim cos que els conté a tots ells, deduïm que $\Fpbar$ és una clausura algebraica.
:::

::: {.corollary}
Si $\FF$ és un cos finit, aleshores $\bar{\FF}=\Fpbar$.
:::
::: {.proof}
Ja hem vist que $\bar{\FF}$ és el conjunt de tots els elements de $\Fpbar$ que són algebraics sobre $\FF$, i això és tot $\Fpbar$.
:::


## El lema de Zorn

El lema de Zorn és una conseqüència de l'Axioma de l'Elecció. De fet, els dos són equivalents en la teoria de conjunts de Zermelo-Fränkel.

::: {.theorem #lema-zorn name="lema de Zorn"}
Sigui $X$ un conjunt no buit amb un ordre parcial $\leq$. Suposem que tota cadena no buida $Y\subseteq X$ té una fita superior $x\in X$.
Aleshores $X$ té algun element maximal.
:::

Una aplicació típica del Lema de Zorn és el següent resultat de teoria d'anells.

::: {.proposition #ideal-maximal name="tot anell té maximal"}
Sigui $A$ una anell unitari no trivial. Aleshores existeix un ideal maximal $I\subset A$.
:::
::: {.proof}
Sigui $X$ el conjunt de tots els ideals propis d'$A$, que és no buit perquè $(0)\in X$. La inclusió ens dona un ordre parcial a $X$, i
un ideal maximal d'$A$ és el mateix que un element maximal a $X$. Només ens cal, doncs, verificar les hipòtesis del lema de Zorn.

Sigui $T\subseteq X$ una cadena no buida, i sigui $I$ l'ideal obtingut fent la unió de tots els elements de $T$. Fent servir
que $T$ és totalment ordenat, és fàcil veure que $I$ és un ideal. Ens falta veure que és propi, és a dir, que $1\notin I$. Però si
$1\in I$, aleshores hi ha algun membre de $T$ que conté $1$, i per tant no seria un ideal propi, contradicció.  
:::

## Existència i unicitat de la clausura algebraica

Donat un cos qualsevol $F$, tenim ara l'objectiu de construir una clausura algebraica $\bar{F}/F$. Intuitivament almenys,
la idea és de considerar, per cada polinomi $g(x)\in F[x]$, un cos $F_g$ que contingui totes les arrels de $g$.
Aleshores hauríem de prendre el compositum de tots aquests cossos. El problema és que per fer el compositum
hem de prendre una intersecció de molts cossos, i no està clar on viuen aquests cossos (la intersecció
de conjunts només té sentit quan aquests conjunts són subconjunts d'un conjunt fixat). Fixem-nos que si
només consideréssim un nombre finit de polinomis $g_1(x),\ldots, g_n(x)$ aleshores podríem prendre
el cos de descomposició del producte $g_1(x)\cdots g_n(x)$.

::: {.theorem #existencia-clausura-algebraica name="existència de clausura algebraica"}
Sigui $F$ un cos. Aleshores existeix una clausura algebraica $\bar{F}/F$.
:::
::: {.proof}
Considerem un conjunt $\mathcal{U} \supset F$ de cardinal estrictament superior a $\mathcal{N}=\max(\aleph_0, |F|)$.

Sigui
$$X = \{K\subseteq L \subseteq \mathcal{U} ~|~ L/K \text{ és una extensió algebraica de $K$}\},$$
amb la relació d'ordre
$$
K_2 > K_1 \iff \text{$K_2/K_1$ és una extensió algebraica}.
$$
Com que tota cadena d'$X$ té un element maximal (prenem la unió de totes les extensions de la cadena), el lema de Zorn
ens diu que hi ha un element maximal a $X$, que anomenarem $\bar{F}$. Només ens cal veure que $\bar{F}/F$ és
una clausura algebraica. Sigui $f(x)\in F[x]$ un polinomi no constant, i suposem que no té cap zero a $\bar{F}$.
Podem construir una extensió $L / \bar{F}$ on $f(x)$ tingui un zero. Aleshores $L/F$ és algebraica, i per tant
$$
|\bar{F}| \leq |L| \leq \mathcal{N}.
$$
Per tant, $|\mathcal{U}\smallsetminus \bar{K}| = |\mathcal{U}| > |L\smallsetminus \bar{K}|$. Això fa que existeixi
una aplicació (de conjunts) injectiva $i \colon L \to \mathcal{U}$ tal que $i(x)=x$ si $x\in \bar{F}$. Podem doncs
transportar l'estructura de cos de $L$ a $i(L)$ i obtenim un nou element maximal $L > \bar{F}$, contradient
la maximalitat de $\bar{F}$.
:::

Una demostració alternativa:
::: {.proof}
Presentem una demostració alternativa que amaga una mica més els problemes amb la teoria de conjunts. Gràcies
a la Proposició \@ref(prp:clausura-tecnica), n'hi ha prou amb construir una extensió $K/F$ algebraicament tancada.

Per
cada polinomi mònic no constant $f=f(x)\in F[x]$, considerem una variable $x_f$. Tenim l'anell de polinomis
en infinites variables $F[\{x_f\}]$, i hi podem considerar l'ideal $I$ generat pels polinomis $f(x_f)$.

Veurem que $I$ no és el total i, per la Proposició \@ref(prp:ideal-maximal), està contingut en un ideal maximal $\mathcal{M}$. El cos
obtingut prenent el quocient per $\mathcal{M}$
l'anomenem $K_1$, que és una extensió de $F$ que conté **una arrel** de cada polinomi amb coeficients a $F$. Podem
iterar el procés (començant amb $K_1$ en comptes de $F$) per obtenir $K_2/K_1$, una extensió on tot polinomi
amb coeficients a $K_1$ té una arrel, i així construim una successió de cossos de la qual en podem
prendre la seva "unió" $K$. Donat un polinomi $f(x)\in K[x]$, tots els seus coeficients viuen necessàriament
a $K_n$ per algun $n\geq 1$ i, per tant, $f(x)$ té alguna arrel a $K_{n+1}$ i, per tant a $K$.

Ens queda per veure que $I$ és un ideal propi. Suposem que no i arribarem a contradicció. Suposem que tenim una
relació
$$
g_1 f_1(x_{f_1}) + g_2 f_2(x_{f_2}) + \cdots + g_k f_k(x_{f_k}) = 1,\quad g_i \in F[\{x_f\}].
$$
En total, aquesta relació només involucra un nombre finit de variables. Les hi posem nom: denotem $x_1=x_{f_1}$,
i així successivament fins a $x_k = x_{f_k}$. Després anomenem $x_{k+1},\ldots, x_r$ la resta de variables
que apareixen en els polinomis $g_i$, de manera que podem reescriure la relació anterior com
$$
g_1(x_1,\ldots, x_r) f_1(x_1) + g_2(x_1,\ldots,x_r) f_2(x_2)+\cdots+g_k(x_1,\ldots x_r) f_k(x_k)=1.
$$
Prenem ara una extensió finita $F'/F$ que contingui una arrel $\alpha_i$ de $f_i(x)$ per cada $i$. La relació
anterior particularitza, si fem $x_i=\alpha_i$ per $i=1,\ldots,k$ i $x_i=0$ per $i>k$, a $0=1$, que és una
contradicció. Això acaba la demostració.
:::

Veurem ara la unicitat de la clausura algebraica.

::: {.theorem name=""}
Sigui $K/F$ una extensió algebraica, i sigui $L/F$ una extensió algebraicament tancada. Aleshores existeix un
$F$-morfisme $K\to L$.
:::

::: {.proof}
Considerem el conjunt de tots els morfismes $\varphi\colon K' \to L$, on $F \subseteq K'\subseteq K$. Aquest
conjunt té un ordre parcial: $\varphi\leq \psi$ si i només si $\psi$ extén $\varphi$. Podem aplicar fàcilment
el lema de Zorn per obtenir un element maximal $\varphi \colon K' \to L$. Cal veure que $K'=K$. Però si no ho fos, podem prendre
un element $\alpha\in K\smallsetminus K'$, i estendre el morfisme $\varphi$ a $K'(\alpha)$, ja que $L$ té una arrel del
polinomi mínim d'$\alpha$, contradient la maximalitat de $K'$.
:::

::: {.corollary #unititat-clausura-algebraica name="unicitat de la clausura algebraica"}
Siguin $K/F$ i $L/F$ clausures algebraiques de $F$. Aleshores $K\cong L$.
:::

::: {.proof}
Apliquem el teorema anterior i obtenim un $F$-morfisme $\varphi\colon K \to L$, que és injectiu. Sigui $\beta\in L$ un
element qualsevol, i sigui $f(x)$ el seu polinomi mínim sobre $F$. Com que $K$ és algebraicament tancat, conté totes les
arrels de $f(x)$, i $\varphi$ indueix una aplicació injectiva (i per tant exhaustiva) entre elles. Així, hi ha alguna arrel
$\alpha\in K$ tal que $\varphi(\alpha)=\beta$, i hem demostrat que $\varphi$ és exhaustiu.
:::

::: {.remark}
L'existència i unicitat de clausures algebraiques fou demostrada per Steinitz el 1910, i la demostració era molt
més llarga i complicada (unes 20 pàgines).

També es pot demostrar (però ens cal teoria que veurem una mica més endavant) que el cos $K_1$
que apareix a la demostració anterior ja és algebraicament tancat, així que no caldria fer tots
els altres infinits passos. La demostració d'aquest fet no és senzilla, fa servir el teorema de l'element
primitiu (vegeu \@ref(element-primitiu)), i separa els casos de característica $0$ i característica $p$.
:::
