# Polinomis Ciclotòmics {#ciclotomics}


L'objectiu principal és demostrar que l'extensió ciclotòmica $\QQ(\zeta_n)$ té grau $\varphi(n)$ (la phi d'Euler). Per això,
introduïrem els polinomis ciclotòmics, veurem que són irreductibles i mònics i tenen coeficients enters.

## Definició

Sigui $\mu_n$ el grup de les arrels $n$-èssimes de la unitat, que podem pensar dins de $\CC$.
Com a grup abstracte, és isomorf a $\ZZ/n\ZZ$ (un cop fixem una arrel primitiva $\zeta_n$):
$$
\ZZ/n\ZZ \to \mu_n,\quad a \mapsto \zeta_n^a.
$$
Ja hem observat que les arrels primitives són exactament les de la forma $\zeta_n^a$ amb $a$ coprimer amb $n$
i que, per tant, n'hi ha $\varphi(n)$. Fixem-nos també que si $d\mid n$ aleshores $\mu_d \subseteq \mu_n$.
Però fixem-nos que si $\zeta\in \mu_n$, aleshores $\zeta$ és una arrel primitiva $d$-èssima per algun $d \mid n$.

::: {.definition #polinomi-ciclotomic name="polinomi ciclotòmic"}
El *polinomi ciclotòmic $n$-èssim* $\Phi_n(x)$ és el polinomi de grau $\varphi(n)$ que té per arrels
les arrels primitives de la unitat:
$$
\Phi_n(x) = \prod_{\substack{1\leq a \leq n\\\mcd(a,n)=1}} (x-\zeta_n^a).
$$
:::

## Càlcul recursiu

Tenim la factorització
$$
x^n - 1= \prod_{\zeta \in \mu_n} (x-\zeta) = \prod_{d\mid n} \Phi_d(x).
$$
En particular, comparant graus tenim la identitat
$$
n = \sum_{d \mid n} \varphi(d).
$$


A més, fixem-nos que la fórmula anterior ens permet calcular els polinomis ciclotòmics de manera recursiva,
dividint pels factors coneguts:
\begin{equation}
\Phi_n(x) = \frac{x^n - 1}{\prod_{\substack{d \mid n\\d < n}} \Phi_d(x)}.
(\#eq:ciclotomics-recursius)
\end{equation}


Els primers valors són, per exemple:

\begin{align*}
\Phi_1(x) &= x-1\\
\Phi_2(x) &= x+1\\
\Phi_{3}(x) &= x^{2} + x + 1 \\
\Phi_{4}(x) &= x^{2} + 1 \\
\Phi_{5}(x) &= x^{4} + x^{3} + x^{2} + x + 1 \\
\Phi_{6}(x) &= x^{2} - x + 1 \\
\Phi_{7}(x) &= x^{6} + x^{5} + x^{4} + x^{3} + x^{2} + x + 1 \\
\Phi_{8}(x) &= x^{4} + 1 \\
\Phi_{9}(x) &= x^{6} + x^{3} + 1 \\
\Phi_{10}(x) &= x^{4} - x^{3} + x^{2} - x + 1 \\
\Phi_{11}(x) &= x^{10} + x^{9} + x^{8} + x^{7} + x^{6} + x^{5} + x^{4} + x^{3} + x^{2} + x + 1 \\
\Phi_{12}(x) &= x^{4} - x^{2} + 1 \\
\Phi_{13}(x) &= x^{12} + x^{11} + x^{10} + x^{9} + x^{8} + x^{7} + x^{6} + x^{5} + x^{4} + x^{3} + x^{2} + x + 1
\end{align*}

::: {.lemma}
Els polinomis $\Phi_n(x)$ són mònics de grau $\varphi(n)$ i tenen coeficients enters.
:::
::: {.proof}
L'únic que ens cal veure és que $\Phi_n(x)$ té coeficients enters. Això es veu fàcilment per inducció en $n$
i l'algoritme de divisió, fent servir la fórmula \@ref(eq:ciclotomics-recursius).
:::

## Irreductibilitat

Amb una mica més de feina podem veure que també són irreductibles.

::: {.theorem #ciclotomics-irreductibles}
Els polinomis $\Phi_n(x)$ són irreductibles.
:::
::: {.proof}
Prenem $n\geq 3$, i escrivim una factorització $\Phi_n(x)=f(x)g(x)$ amb $f(x)$ i $g(x)$ mònics a $\ZZ[x]$, i amb $f(x)$
irreductible de grau com a mínim $2$. L'objectiu és demostrar que $f(x)=\Phi_n(x)$, és a dir, que tota arrel primitiva $n$-èssima
és arrel de $f(x)$. Sigui doncs $\zeta$ una arrel $n$-èssima primitiva que sigui arrel de $f(x)$, i veurem
que $\zeta^a$ també és arrel de $f(x)$ per a tot $a$ coprimer amb $n$.

TODO
:::

::: {.corollary}
El cos ciclotòmic $\QQ(\zeta_n)$ té grau $\varphi(n)$ sobre $\QQ$.
:::