# Teoria de Galois infinita

Farem un esbós de com cal modificar els enunciats per adaptar el teorema fonamental de la Teoria de Galois
a extensions infinites.

## Definicions

Sigui $K/F$ una extensió algebraica arbitraria. Per definir què vol dir *Galois*, no ens anirà
bé mirar el cardinal d'$\Aut(K/F)$, perquè en general serà un grup infinit. En canvi,
una de les caracteritzacions que hem trobat sí que generalitza bé.

::: {.definition}
L'extensió $K/F$ és una *extensió de Galois* si és normal i separable. És a dir, si per tot $\alpha\in K$
el polinomi $\Irr_{\alpha,F}(x)$ descomposa completament a $K$ en factors simples.
:::

::: {.example}
Podem donar els exemples de $\bar{\QQ} / \QQ$, de $\QQ(\zeta_{p^\infty})$ i de $\bar{\FF}_p / \FF_p$.
:::

::: {.definition name="grup de Galois"}
Si $K/F$ és de Galois, aleshores el seu *grup de Galois* és el grup $\Gal(K/F)$ format
pels automorfismes de $K$ que fixen $F$.
:::

Suposem a partir d'ara que $L/K$ és un extensió de Galois (que pot ser infinita).

::: {.lemma}
Sigui $E/F$ una subextensió de $L/K$. Aleshores $L/E$ també és de Galois.
:::
::: {.proof}
Sigui $\alpha \in L$. Aleshores $\Irr_{\alpha,E}(x)$ és un divisor de $\Irr_{\alpha,F}(x)$. Per tant,
és separable i té totes les arrels a $L$.
:::

Necessitem el següent resultat tècnic.

::: {.proposition}
Sigui $K/M/F$ una subextensió, i sigui $\tilde\sigma\colon M\to K$ un $F$-morfisme. Aleshores
existeix $\sigma\in\Gal(K/F)$ tal que $\sigma|_M = \tilde\sigma$.
:::

::: {.proof}
Fem servir el Lema de Zorn. Donada una cadena d'extensions, podem prendre com a element
maximal la unió d'aquestes, i $\tilde\sigma$ hi extén. Si $\sigma'\colon L'\to L$ és l'element maximal donat per Zorn,
volem veure que $L'=L$. Si no ho fos, prenem $\alpha\in L\smallsetminus L'$ i extenem el morfisme (ho podem fer perquè estem en el
cas finit), cosa que és una contradicció.

Veiem que l'extensió $\sigma$ és exhaustiva fent servir que permuta les arrels del polinomi mínim de qualsevol element.
:::

::: {.lemma}
Sigui $E/F$ una subextensió finita i Galois de $K$. Aleshores la restricció indueix un morfisme de grups
$$
\res\colon \Gal(K/F)\to \Gal(E/F)
$$
que és exhaustiu.
:::
::: {.proof}
Només cal observar que si $\sigma\in\Gal(K/F)$ aleshores $\sigma(E)=E$, ja que $\sigma$ permuta les arrels
del polinomi mínim de qualsevol element d'$E$, i aquestes viuen totes a $E$. La proposició anterior
ens dona l'exhaustivitat.
:::

Donat un subgrup $H\leq \Gal(K/F)$, podem considerar el cos fix $K^H$. També donat una subcos $K/M/F$, podem
considerar el subgrup $\Gal(K/M)\leq \Gal(K/F)$.

::: {.example}
Considerem l'extensió de Galois infinita $\Fpbar/\FF_p$, amb $\Fpbar = \bigcup_{n\geq 1} \FF_{p^n}$, i l'automorfisme $\pi \colon\bar{\FF}_p\to\bar{\FF}_p$,
que envia $x\mapsto x^p$. El cos fix per $\pi$ és $\FF_p$. Veurem que $\FF_p$ no està generat per $\pi$ i per
tant el teorema fonamental de la teoria de Galois no pot ser cert en aquest context.

Construirem un element de $\sigma \in \Gal(\Fpbar/\FF_p)$ tal que $\sigma\neq \pi^n$ per cap $n$. Considerem
l'extensió $M=\bigcup_{n\geq 1} \FF_{p^{2n+1}}$, que és infinita i no conté $\FF_{p^2}$, per tant no és tot $\bar{\FF}_p$.
Prenem $\alpha\in\Fpbar\smallsetminus M$ i considerem una arrel $\beta$ conjugada d'$\alpha$ sobre $M$. Hi ha
un element de $\Gal(M'/M)$ que envia $\alpha\mapsto \beta$ ($M'$ el cos de descomposició de $\Irr_{\alpha,M}(x)$)
i per tant, pel l'exhaustivitat de la restricció, trobem $\sigma\in\Gal(\Fpbar / M)$ que envia $\alpha\mapsto\beta$.
El cos fix per $\sigma$ conté $M$, que és un cos infinit. En canvi, per cada $n$ el cos fix per $\pi^n$ és el cos
finit de $p^n$ elements. Per tant $\sigma\neq \pi^n$.
:::

En l'apartat següent veurem com corregir aquest problema, que és que hi ha massa subgrups de subgrups, i no tots
es poden correspondre a subextensions. Per tant, la solució consistirà en restringir els possibles subgrups
que considerem.

## La topologia de Krull

Ajuntant tots els morfismes restricció de l'apartat anterior, obtenim una aplicació
$$
\iota \colon \Gal(K/F) \to \prod_{E / F\text{ finita Galois}} \Gal(E/F).
$$
Aquest morfisme de grups és injectiu, ja que tot $\alpha\in K$ viu en una extensió finita i Galois (per exemple,
la clausura de Galois de $F(\alpha)/F$). La imatge de $\iota$ està formada per aquells elements $(\sigma_E)_E$
del producte cartesià tals que $(\sigma_E)|_{E'} = \sigma_{E'}$ per
a tota parella de subextensions finites Galois $E'\subset E$.

Els grups que apareixen a la dreta són tots finits, i podem considerar
la topologia discreta en cadascun d'ells. Aleshores podem posar la topologia del producte en el producte (infinit),
i com que $\Gal(K/F)$ s'identifica amb un subconjunt, li podem donar la topologia del subespai.

::: {.definition #topologia-krull name="topologia de Krull"}
La *topologia de Krull* a $\Gal(K/F)$ és la topologia obtinguda amb el procediment anterior.
:::

::: {.proposition}
Els conjunts
$$
U_{\sigma, E} = \{\tau \in \Gal(K/F) ~|~ \tau|_E = \sigma|_E\},
$$
on $E$ recorre les subextensions finites Galois $E/F$ formen una base d'entorns de $\sigma$.
:::
::: {.proof}
Veiem primer que si $E_0/F$ és una subextensió finita Galois aleshores $U_{\sigma,E_0}$ és un obert. El conjunt
$$
V_{\sigma,E_0} = \{\sigma|_{E_0}\} \times \prod_{E\neq E_0} \Gal(K/E) \subseteq \prod \Gal(K/E)
$$
és un obert, i satisfà
$$
\iota(U_{\sigma,E_0}) = V_{\sigma,E_0} \cap \iota(\Gal(K/F)).
$$

Ara només ens cal veure que, donat un obert qualsevol $V$, podem trobar $\sigma$ i $E_0$ tal que $U_{\sigma,E_0}\subseteq V$. N'hi
ha prou amb veure-ho per una base d'oberts del producte, és a dir, podem pensar que $\iota(V)$ és de la forma
$$
\iota(V) = V_{E_1}\times V_{E_2}\times\cdots V_{E_k} \times \prod_{E\neq E_i} \Gal(K/E).
$$
Prenem $\sigma\in V\subseteq \Gal(K/F)$ i considerem $E_0=E_1E_2\cdots E_k$. Aleshores
$$
\iota(\sigma) \in \iota(U_{\sigma, E_0}) \subseteq \{\sigma|_{E_1}\} \times \{\sigma|_{E_2}\}\times\cdots\times \{\sigma|_{E_1}\} \times \prod_{E\neq E_i} \Gal(E/F).
$$
:::

::: {.proposition}
El grup $\Gal(K/F)$ és tancat a $\prod_{E/F} \Gal(E/F)$.
:::
::: {.proof}
Sigui $(\sigma_E)_E$ un element del producte que no ve de $\Gal(K/F)$. Això vol dir que hi ha
extensions finites $E_0\subseteq E_1$ tals que $(\sigma_{E_1})|_{E_0}\neq \sigma_{E_0}$. Aleshores el conjunt
$$
\{\sigma_{E_0}\} \times \{\sigma_{E_1}\} \times \prod_{E \neq E_0, E_1} \Gal(E/K)
$$
és un obert que conté $(\sigma_E)_E$ i no interseca la imatge de $\Gal(K/F)$.
:::
::: {.corollary}
El grup $\Gal(K/F)$ és compacte.
:::
::: {.proof}
Pel teorema de Tychonoff, el producte infinit és compacte, i un subespai tancat d'un compacte és compacte.
:::

Això ens permet donar una condició necessària per ser grup de Galois d'una subextensió:

::: {.proposition}
Sigui $M/F$ una subextensió de $K/F$. Aleshores $\Gal(K/M)$ és tancat a $\Gal(K/F)$.
:::
::: {.proof}
Veurem que el complementari és obert. Sigui $\sigma\in \Gal(K/F)\smallsetminus \Gal(K/M)$.
Per tant, existeix $\alpha\in M\smallsetminus F$ tal que $\sigma(\alpha)\neq \alpha$. Sigui $E/F$
una extensió finita Galois que contingui $\alpha$. Aleshores
$$
U_{\sigma, E} \subseteq \Gal(K/F)\smallsetminus \Gal(K/M).
$$
En efecte, si $\tau\in U_{\sigma, E}$, vol dir que $\tau(\alpha)\neq \alpha$, i per tant $\tau\not\in\Gal(K/M)$.
:::

A l'apartat següent veurem que aquesta condició també és suficient. És a dir,
que els subgrups tancats de $\Gal(K/F)$ es corresponen amb les subextensions

## El teorema

Podem ja enunciar i demostrar el teorema fonamental.

::: {.theorem name="teorema fonamental de la teoria de Galois infinita"}
Sigui $K/F$ una extensió de Galois. La correspondència de Galois estableix una bijecció entre els subcossos
$K/M/F$ i els subgrups *tancats* de $\Gal(K/F)$.
:::
::: {.proof}
L'únic que no és obvi és el fet, donat un subgrup tancat $H$, si definim $M=K^H$ aleshores
$\Gal(K/M) = H$. De fet, la inclusió $\supseteq$ és trivial, i només cal veure $\subseteq$.

Sigui $\sigma \in \Gal(K/M)$. Veurem que $U_{\sigma, E} \cap H \neq \emptyset$ per tota extensió
finita Galois $E/F$. Això voldrà dir que $\sigma \in \overline H$ i, com que $H$ és tancat, $\sigma\in H$.

Per veure que $U_{\sigma, E} \cap H \neq \emptyset$, considerem el cos $E'=EM$,
que és una extensió finita Galois de $M$. N'hi haurà prou amb veure $U_{\sigma, E'}\cap H \neq \emptyset$, ja que $U_{\sigma,E'}\subseteq U_{\sigma,E}$.
En aquest cas, la restricció $H \to \Gal(E'/M)$ és exhaustiva. Per tant tenim $\res(H)=\res(\Gal(K/M))$. És a dir,
per tot $\sigma\in\Gal(K/M)$, hi ha $\tau\in H$ tal que $\sigma|_{E'} = \tau|_{E'}$. Per tant, $\tau\in U_{\sigma, E'}\cap H$.
:::

La correspondència de Galois gira els reticles (la demostració és igual que en el cas finit), i a més satisfà les següents propietats:

::: {.proposition}
1. Un subgrup tancat $H\leq \Gal(K/F)$ és obert si i només si té índex finit, i aleshores
$$
[\Gal(K/F) \colon H] = [K^H \colon F].
$$
2. Un subgrup tancat $H\leq \Gal(K/F)$ és normal si i només si $K^H / F$ és Galois, i aleshores
$$
\Gal(K^H/ F) \cong \Gal(K/F) / H.
$$
:::
::: {.proof}
1. Si $H$ és d'índex finit, llavors $\Gal(K/F) = \bigcup_\sigma \sigma(H)$, on $\sigma$ recorre un conjunt (finit)
  de representants de les classes laterals d'$H$ (assumim que un dels representants és $1$). Per tant, el complementari d'$H$
  està format per una unió finita de tancats ($\sigma$ és tancada, perquè és un automorfisme continu) i per tant és un tancat (i $H$ és un obert).

  Recíprocament, si $H$ és obert llavors el complementari és tancat i per tant compacte (ja hem vist que $\Gal(K/F)$ és compacte). Tenim
  un recobriment per oberts del complementari com a $\bigcup_{\sigma\neq 1} \sigma(H)$ i, per compacitat, hi ha un subrecobriment finit. Això
  vol dir que $\Gal(K/F)$ és una unió finita de classes laterals d'$H$ i per tant $H$ té índex finit.
2. Definim $E=K^H$. Donats automorfismes $\sigma,\tau\in\Gal(K/F)$, i donat $\alpha\in K$, tenim
  $$
  \tau\alpha=\alpha \iff \sigma\tau\sigma^{-1}(\sigma\alpha)=\sigma(\alpha).
  $$
  Per tant, $\Gal(K/\sigma(E)) =\sigma\Gal(K/E)\sigma^{-1} = \sigma H\sigma^{-1}$. D'aquí en traiem que $H$ és normal
  si i només si $\sigma(E) = E$ per tot $\sigma\in \Gal(K/F)$, i això és equivalent a que $E/F$ sigui Galois. L'isomorfisme
  es demostra igual que en el cas finit.
:::

::: {.example name="grup de Galois de $\QQ(\zeta_{p^\infty}) / \QQ$"}
Considerem la unió infinita $K=\bigcup_{n\geq 1} \QQ(\zeta_{p^n})$. Es té un morfisme injectiu
$$
\iota \colon \Gal(K/\QQ) \injects \prod_{n\geq 1} \Gal(\QQ(\zeta_{p^n}) / \QQ) \cong \prod_{n\geq 1} \left(\ZZ/p^n\ZZ\right)^\times,
$$
on la última identificació ve de fer correspondre $a_n \in \left(\ZZ/p^n\ZZ\right)^\times$ amb $\sigma_{a_n}\colon \zeta_{p^n} \mapsto \zeta_{p^n}^{a_n}$.
La imatge de $\iota$ està formada per aquells elements $(\sigma_{a_n})_n$ del producte que són compatibles amb la restricció.
Com que si $\sigma_{a_{n+1}}(\zeta_{p^{n+1}}) = \zeta_{p^{n+1}}^{a_{n+1}}$ aleshores
$\sigma_{a_{n+1}}(\zeta_{p^n}) = \zeta_{p^n}^{a_{n+1}}$,
la condició de ser compatible amb la restricció és equivalent a la condició $a_{n+1} \equiv a_n \pmod{p^n}$. Concloem que
$$
\Gal(K/\QQ) \cong \{(a_n)_{n\geq 1} \in \prod_{n\geq 1} \left(\ZZ/p^n\ZZ\right)^\times ~|~ a_{n+1}\equiv a_n \pmod{p^n}\} = \ZZ_{p}^\times,
$$
on el grup $\ZZ_{p}^\times$ és el grup d'unitats de l'anell dels enters $p$-àdics. Fixem-nos que aquest grup és no-numerable, mentre
que hi ha una quantitat numerable de subcossos de $K$.
:::


::: {.example name="grup de Galois de $\Fpbar / \FF_p$"}
Considerem en aquest cas l'extensió $\Fpbar / \FF_p$. Tenim un morfisme injectiu
$$
\iota \colon \Gal(\Fpbar/\FF_p) \injects \prod_{n\geq 1} \Gal(\FF_{p^n}/\FF_p) \cong \prod_{n\geq 1} \ZZ/n\ZZ,
$$
fent correspondre $a\in\ZZ/n\ZZ$ amb la potència del Frobenius $\pi^a$. Si $n\mid m$, hi ha el morfisme de restricció
$$
\Gal(\FF_{p^m}/\FF_p) \to \Gal(\FF_{p^n}/\FF_p),
$$
que es correspon amb l'aplicació natural $\ZZ/m\ZZ\to \ZZ/n\ZZ$. Per tant,
$$
\Gal(\Fpbar/\FF_p) \cong \{(a_n)_{n} \in \prod_{n\geq 1}\ZZ/n\ZZ ~|~ \forall n\mid m, a_m \equiv a_n \pmod{n}\} = \hat{\ZZ},
$$
on $\hat{Z}\cong \prod_{p} \ZZ_p$ és la *completació finita* dels enters.
:::

