on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install latex mk
        run: sudo apt-get udpate & sudo apt-get install -y -q r-base latexmk texlive-latex-extra texlive-xetex fonts-freefont-ttf texlive-fonts-recommended texlive-fonts-extra
      - name: Install python Lean dependencies
        run: python -m pip install --upgrade pip
      - name : Make documentation
        run: ./build.sh
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.github_token }}
          publish_dir: ./_book/
